global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#maksim_gorbachev'

