version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui
    ports:
      - ${UI_SERVICE_PORT}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKEND_NET}
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONTEND_NET}

