kind: EncryptionConfig
apiVersion: v1
resources:
- resources:
    - secrets
    providers:
    - aescbc:
        keys:
            - name: key1
            secret: ZX3Lf4XiD/hdvWMRH7yrHYYCJ9inBZM0eAkATtJl8zA=
    - identity: {}
