---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - image: max2l/post:3.0
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: post-db
        - name: POST_DATABASE
          value: posts
