- name: Configule application
  become: true
  hosts: tag_reddit-docker
  tasks:
    - name: Install packedges for docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add docker apt repo key
      apt_key:
        keyserver: get.docker.com
        id: 0EBFCD88

    - name: Add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - python-docker
        state: present
        update_cache: yes
