kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: Us0MvW/R4guNBqmcLGtCnCElgANlVJPfI0R/aFcUpOw=
      - identity: {}
