kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: XZBm7DfczWph7rmbciBoEZsIUhx7xD7kF//6MZVuGTY=
      - identity: {}
