version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: mongo_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    container_name: ui
    hostname: ui
    ports:
      - ${UI_SERVICE_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST}
    hostname: post
    container_name: post
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    hostname: comment
    container_name: comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONTEND_NET}
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKEND_NET}
