version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${UI_SERVICE_PORT}:9292/tcp
    networks:
      - front_net
    volumes:
      - type: bind
        source: ./ui
        target: /app
        read_only: true

  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - back_net
      - front_net
    volumes:
      - type: bind
        source: ./post-py
        target: /app
        read_only: true

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - back_net
      - front_net
    volumes:
      - type: bind
        source: ./comment
        target: /app
        read_only: true

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKEND_NET}
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONTEND_NET}
